# Generated by Django 3.1.3 on 2023-02-16 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0002_auto_20230214_1500'),
        ('trains', '0002_auto_20230215_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traintest',
            name='travel_time',
        ),
        migrations.AlterField(
            model_name='traintest',
            name='from_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_city', to='cities.city', verbose_name='Из какого города'),
        ),
        migrations.AlterField(
            model_name='traintest',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Номер поезда'),
        ),
    ]
